#server:
#  port: 8899
#
#spring:
#  application:
#    name: ollama-chat-dome
#  ai:
#    openai:
#      api-key: sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
#      base-url: http://localhost:11434
#      chat:
#        options:
#          model: deepseek-r1:1.5b
#          temperature: 0.7


server:
  port: 8899

spring:
  application:
    name: ollama-chat-dome
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: deepseek-r1:1.5b
          temperature: 0.7